### PR TITLE
Fix broken dependency

### PR DESCRIPTION
**Pull request by shogo82148**

### CODE REVIEW

**Comment by vlashef** [comment]
Awesome Thank you!

**Comment by shogo82148** [comment]
But, it still doesn't work... 🤔

**Comment by vlashef** [comment]
Yes I noticed also but wasn’t sure if you had pushed updates yet to the
layer.

**Comment by vlashef** [comment]
Thank you for fixing this dependency issue, however I don't know if it is completely resolved.

  "errorMessage": "\n\nTrace begun at /opt/lib/perl5/site_perl/5.34.0/Paws/Net/XMLResponse.pm line 1\nPaws::Net::XMLResponse::unserialize_response('Paws::Net::XMLResponse=HASH(0x37753b0)', 'Paws::Net::APIResponse=HASH(0x3663198)') called at /opt/lib/perl5/site_perl/5.34.0/Paws/Net/XMLResponse.pm line 1\nPaws::Net::XMLResponse::response_to_object('Paws::Net::XMLResponse=HASH(0x37753b0)', 'Paws::STS::GetCallerIdentity=HASH(0x3775908)', 'Paws::Net::APIResponse=HASH(0x3663198)') called at /opt/lib/perl5/site_perl/5.34.0/Paws/Net/XMLResponse.pm line 1\nPaws::Net::XMLResponse::process('Paws::Net::XMLResponse=HASH(0x37753b0)', 'Paws::STS::GetCallerIdentity=HASH(0x3775908)', 'Paws::Net::APIResponse=HASH(0x3663198)') called at /opt/lib/perl5/site_perl/5.34.0/Paws/Net/Caller.pm line 1\nPaws::Net::Caller::caller_to_response('Paws::Net::Caller=HASH(0x2fceb38)', 'Paws::STS=HASH(0x335ce38)', 'Paws::STS::GetCallerIdentity=HASH(0x3775908)', 'Paws::Net::APIResponse=HASH(0x3663198)') called at /opt/lib/perl5/site_perl/5.34.0/Paws/Net/RetryCallerRole.pm line 1\nPaws::Net::RetryCallerRole::do_call('Paws::Net::Caller=HASH(0x2fceb38)', 'Paws::STS=HASH(0x335ce38)', 'Paws::STS::GetCallerIdentity=HASH(0x3775908)') called at /opt/lib/perl5/site_perl/5.34.0/Paws/STS.pm line 1\nPaws::STS::GetCallerIdentity('Paws::STS=HASH(0x335ce38)') called at /var/task/script.pl line 16\nmain::get_aws_account at /var/task/script.pl line 260\nmain::handle at /var/task/script.pl line 321\nrequire /var/task/script.pl at /opt/lib/perl5/vendor_perl/5.34.0/AWS/Lambda/Bootstrap.pm line 70\nAWS::Lambda::Bootstrap::try {...}  at /opt/lib/perl5/vendor_perl/5.34.0/Try/Tiny.pm line 100\neval {...} at /opt/lib/perl5/vendor_perl/5.34.0/Try/Tiny.pm line 93\nTry::Tiny::try('CODE(0xb128a8)', 'Try::Tiny::Catch=REF(0xaff7c8)') called at /opt/lib/perl5/vendor_perl/5.34.0/AWS/Lambda/Bootstrap.pm line 77\nAWS::Lambda::Bootstrap::_init('AWS::Lambda::Bootstrap=HASH(0xb12800)') called at /opt/lib/perl5/vendor_perl/5.34.0/AWS/Lambda/Bootstrap.pm line 53\nAWS::Lambda::Bootstrap::handle_events('AWS::Lambda::Bootstrap=HASH(0xb12800)') called at /opt/lib/perl5/vendor_perl/5.34.0/AWS/Lambda/Bootstrap.pm line 21\nAWS::Lambda::Bootstrap::bootstrap at /opt/bootstrap line 8\nCompilation failed in require at /opt/lib/perl5/vendor_perl/5.34.0/AWS/Lambda/Bootstrap.pm line 70.\n"


I 3x checked and there are no permission issues/changes (that is all the same as before the issue) , and the code is exceedingly simple as it just looks to grab the account the code is currently operating in:

    my $sts = Paws->service('STS');
    my $GetCallerIdentityResponse = $sts->GetCallerIdentity();
    my $Account = $GetCallerIdentityResponse->Account;

I did a sanity check and did remove that however the same errors occurred later when using S3 Service etc.

I 'think' it has to do with the same SSL issues

**Comment by vlashef** [comment]
oh and yes using layer versions 3 of the same two layers

**Comment by shogo82148** [comment]
Hmmm...
Thank you for your report.
I have same problem on my AWS account.
I'll try to fix it.

**Comment by vlashef** [comment]
Thank you sir!

**Pull request merged**
